name: CI-CD-Pipeline-to-EKS
env:
  AWS_REGION_NAME: "ap-south-1"

on:
  push:
    branches:
      - main

jobs:
  my_ci_cd:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone repo
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.28.0'
      id: install
    
    - name: Configure my AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id    :  ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region           :  ${{ env.AWS_REGION_NAME }}

    - name: Login to Amazon ECR
      id  : login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, push docker image to Amazon ECR
      env :
        REGISTRY       : ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY     : reponame
        IMAGE_TAG      : 1.1
      run : |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 078390452561.dkr.ecr.ap-south-1.amazonaws.com
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      
    - name: Update kube config
      run : aws eks update-kubeconfig --name cluster-name
    
    - name: Deploy to EKS
      run : |
        kubectl apply -f deployment.yaml --context cluster-name
        kubectl apply -f service.yaml --context cluster-name
